### ISSUE TITLE
Search words hidden in drop down

### ISSUE THREAD

**Issue by AdamPS** [jgbishop/googlebarlite#34]
After the latest upgrade to 5.1, the search words shown on the toolbar are grouped under a drop-down even when there is plenty of space for them.  Previously they were directly clickable (as shown in the screenshot on your site http://www.borngeek.com/firefox/googlebarlite/).

I notice the change history for this release says
> Search words are now grouped together under one toolbar button when Googlebar Lite is placed on the nav-bar

So it's possible it's a deliberate change??  But it seems to make the feature much harder to use which is a shame.

**Comment by jgbishop** [comment]
This change was intentional, and only affects the toolbar if it is located on the main navigation bar. Real-estate on that toolbar is valuable, which is why I made the change. If you relocate the toolbar to its own line (or another toolbar), the toolbar will use the old behavior.

**Comment by AdamPS** [comment]
Please, please could you make it an option whether to collapse or expand?  (I would suggest the default to be the original behaviour, but it doesn't matter too much which way.)  It seems such a shame to break the tool for a proportion of your users after all this time.

The workaround of moving all the buttons to another bar is tedious, not widely documented, and not really ideal.  Possibly from time-to-time Firefox will make an important new button appear on the navigation bar and now mine is hidden.  And what if another add-on made behaviour conditional on which bar I was using - it would soon become impossible.

With the popular widescreen format, having just one toolbar is common.  At least for me, Firefox automatically collapses any words where there isn't space on the bar.  So provided the googlebar is the rightmost item it all works fine, best of both worlds.  I suspect it's a popular configuration.  Another person has already commented on https://addons.mozilla.org/en-GB/firefox/addon/googlebar-lite/reviews/ and for every person who asks there are likely 50 who don't.

Thanks!  (PS I will donate if this is fixed again.)
