### ISSUE TITLE
Not working after last firefox update

### ISSUE THREAD

**Issue by nijel8** [jgbishop/googlebarlite#37]
It just refreshes Google page without query the new search words.

**Comment by jgbishop** [comment]
I am unable to reproduce this in Firefox 47. What version of Firefox do you see the problem in? Do you have other add-ons installed? Have you tried disabling other add-ons to see if that helps?

**Comment by nijel8** [comment]
Ignore it...  It was a temporary glitch. It's working now.  Thanks for the reply.
